backend:
  name: git-gateway
  repo: grigorybulgakov/star-wars-ttrpg-by-parade
  branch: main
  identity_url: https://auth.decapbridge.com/sites/838f2fa5-d281-46f1-b42f-c684786dcfe2
  gateway_url: https://gateway.decapbridge.com

site_url: https://grigorybulgakov.github.io/star-wars-ttrpg-by-parade/
logo_url: https://decapbridge.com/decapcms-with-bridge.svg
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - label: "Настройки страницы"
    name: "settings"
    files:
      - label: "Глобальные настройки"
        name: "settings"
        file: "content/settings.json"
        fields:
          - { label: "Заголовок вкладки (HTML <title>)", name: "pageTitle", widget: "string" }
          - label: "Обложка"
            name: "cover"
            widget: "object"
            fields:
              - { label: "Заголовок на обложке", name: "title", widget: "string" }
              - { label: "Подзаголовок (поддерживает HTML)", name: "subtitle", widget: "text" }
              - { label: "Автор / подпись", name: "author", widget: "string", default: "Автор: вы" }
              - label: "Режим даты"
                name: "dateMode"
                widget: "select"
                options:
                  - { label: "Авто (сегодня)", value: "auto" }
                  - { label: "Ручная", value: "manual" }
                default: "manual"
              - { label: "Дата (ДД.ММ.ГГГГ или текст)", name: "dateText", widget: "string", required: false }
              - { label: "Показывать кнопку «Печать в PDF»", name: "showPrintButton", widget: "boolean", default: true }
          - label: "Оглавление (TOC)"
            name: "toc"
            widget: "object"
            fields:
              - label: "Уровни заголовков"
                name: "levels"
                widget: "select"
                multiple: true
                options:
                  - { label: "H2", value: 2 }
                  - { label: "H3", value: 3 }
                default: [2,3]

  - label: "Разделы (с блоками)"
    name: "sections"
    files:
      - label: "Список разделов"
        name: "sections"
        file: "content/sections.json"
        fields:
          - label: "Секции"
            name: "items"
            widget: "list"
            summary: "{{fields.order}} — {{fields.title}}"
            fields:
              - { label: "Заголовок раздела (можно пусто)", name: "title", widget: "string", required: false }
              - { label: "ID (якорь)", name: "id", widget: "string", required: false, hint: "латиница/дефисы, напр. basics, gear" }
              - { label: "Порядок", name: "order", widget: "number", default: 1, min: 0 }
              - { label: "Показывать раздел в оглавлении", name: "includeInTOC", widget: "boolean", default: true }
              - label: "Стиль раздела"
                name: "style"
                widget: "object"
                collapsed: true
                required: false
                fields:
                  - { label: "Верхний отступ", name: "mt", widget: "number", default: 16, min: 0 }
                  - { label: "Нижний отступ", name: "mb", widget: "number", default: 16, min: 0 }
                  - { label: "Внутренний отступ", name: "pad", widget: "number", default: 18, min: 0 }
                  - { label: "Цвет фона", name: "bg", widget: "color", required: false, allowInput: true }
                  - { label: "Цвет текста", name: "text", widget: "color", required: false, allowInput: true }

              - label: "Блоки раздела"
                name: "blocks"
                widget: "list"
                types:
                  - label: "Markdown"
                    name: "markdown"
                    widget: "object"
                    fields:
                      - { label: "Тип", name: "type", widget: "hidden", default: "markdown" }
                      - { label: "Текст (Markdown)", name: "body", widget: "markdown" }
                      - label: "Стиль"
                        name: "style"
                        widget: "object"
                        collapsed: true
                        required: false
                        fields:
                          - { label: "Верхний отступ", name: "mt", widget: "number", default: 16, min: 0 }
                          - { label: "Нижний отступ", name: "mb", widget: "number", default: 16, min: 0 }
                          - { label: "Внутренний отступ", name: "pad", widget: "number", default: 18, min: 0 }
                          - { label: "Цвет фона", name: "bg", widget: "color", required: false }
                          - { label: "Цвет текста", name: "text", widget: "color", required: false }

                  - label: "Подзаголовок"
                    name: "subheading"
                    widget: "object"
                    fields:
                      - { label: "Тип", name: "type", widget: "hidden", default: "subheading" }
                      - { label: "Текст заголовка", name: "title", widget: "string" }
                      - { label: "Показывать в оглавлении", name: "includeInTOC", widget: "boolean", default: true }
                      - { label: "Уровень (2 или 3)", name: "tocLevel", widget: "number", min: 2, max: 3, default: 3 }

                  - label: "Callout / Врезка"
                    name: "callout"
                    widget: "object"
                    fields:
                      - { label: "Тип", name: "type", widget: "hidden", default: "callout" }
                      - { label: "Заголовок (опц.)", name: "title", widget: "string", required: false }
                      - { label: "Показывать в оглавлении", name: "includeInTOC", widget: "boolean", default: false }
                      - { label: "Уровень (2 или 3)", name: "tocLevel", widget: "number", min: 2, max: 3, default: 3 }
                      - { label: "Текст (Markdown)", name: "text", widget: "markdown" }
                      - label: "Стиль"
                        name: "style"
                        widget: "object"
                        collapsed: true
                        required: false
                        fields:
                          - { label: "Верхний отступ", name: "mt", widget: "number", default: 16, min: 0 }
                          - { label: "Нижний отступ", name: "mb", widget: "number", default: 16, min: 0 }
                          - { label: "Цвет фона", name: "bg", widget: "color", required: false }
                          - { label: "Цвет текста", name: "text", widget: "color", required: false }

                  - label: "Таблица"
                    name: "table"
                    widget: "object"
                    fields:
                      - { label: "Тип", name: "type", widget: "hidden", default: "table" }
                      - { label: "Заголовок (опц.)", name: "title", widget: "string", required: false }
                      - { label: "Показывать в оглавлении", name: "includeInTOC", widget: "boolean", default: false }
                      - { label: "Уровень (2 или 3)", name: "tocLevel", widget: "number", min: 2, max: 3, default: 3 }
                      - label: "Колонки"
                        name: "columns"
                        widget: "list"
                        field: { label: "Колонка", name: "col", widget: "string" }
                      - label: "Строки"
                        name: "rows"
                        widget: "list"
                        field:
                          label: "Строка"
                          name: "row"
                          widget: "list"
                          field: { label: "Ячейка", name: "cell", widget: "string" }
                      - label: "Стиль"
                        name: "style"
                        widget: "object"
                        collapsed: true
                        required: false
                        fields:
                          - { label: "Верхний отступ", name: "mt", widget: "number", default: 16, min: 0 }
                          - { label: "Нижний отступ", name: "mb", widget: "number", default: 16, min: 0 }
                          - { label: "Цвет фона", name: "bg", widget: "color", required: false }
                          - { label: "Цвет текста", name: "text", widget: "color", required: false }
