backend:
  name: git-gateway
  repo: grigorybulgakov/star-wars-ttrpg-by-parade
  branch: main
  identity_url: https://auth.decapbridge.com/sites/838f2fa5-d281-46f1-b42f-c684786dcfe2
  gateway_url: https://gateway.decapbridge.com

site_url: https://grigorybulgakov.github.io/star-wars-ttrpg-by-parade/
logo_url: https://decapbridge.com/decapcms-with-bridge.svg
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - label: "Настройки страницы"
    name: "settings"
    files:
      - label: "Глобальные настройки"
        name: "settings"
        file: "content/settings.json"
        fields:
          - { label: "Заголовок вкладки (HTML <title>)", name: "pageTitle", widget: "string" }
          - label: "Обложка"
            name: "cover"
            widget: "object"
            fields:
              - { label: "Заголовок на обложке", name: "title", widget: "string" }
              - { label: "Подзаголовок (поддерживает HTML)", name: "subtitle", widget: "text", hint: "Можно использовать <em>курсив</em>, <strong>жирный</strong> и т.п." }
              - { label: "Автор / подпись", name: "author", widget: "string", default: "Автор: вы" }
              - label: "Режим даты"
                name: "dateMode"
                widget: "select"
                options:
                  - { label: "Авто (сегодня)", value: "auto" }
                  - { label: "Ручная", value: "manual" }
                default: "manual"
              - { label: "Дата (ДД.ММ.ГГГГ или текст)", name: "dateText", widget: "string", required: false }
              - { label: "Показывать кнопку «Печать в PDF»", name: "showPrintButton", widget: "boolean", default: true }

  # (если у тебя есть коллекция «Разделы» — оставь её ниже без изменений)
